import Fastify, { type FastifyError, type FastifyReply, type FastifyRequest } from 'fastify';
import { ZodError } from 'zod';

import { attachApiErrorMessages } from '@encryption/src/server/error-response';
import { corsPlugin } from '@encryption/src/server/plugins/cors';
import { jwtAuthPlugin } from '@encryption/src/server/plugins/jwt-auth';
import { securityHeadersPlugin } from '@encryption/src/server/plugins/security-headers';
import { emergencyAccessRoute } from '@encryption/src/server/routes/emergency-access';
import { meRoute } from '@encryption/src/server/routes/me';
import { publicKeysRoute } from '@encryption/src/server/routes/public-keys';
import { vaultRoute } from '@encryption/src/server/routes/vault';
import { versionRoute } from '@encryption/src/server/routes/versions';
import { API_ERROR_INTERNAL, API_ERROR_INVALID_REQUEST } from '@encryption/src/shared/error-codes';

const isDev = process.env.NODE_ENV === 'development';

// atob() (used by base64ToUint8) throws a DOMException named InvalidCharacterError
// on malformed base64. Recognizing it lets a bad base64 body field be a 400
// rather than an opaque 500.
function isBase64DecodeError(error: unknown): boolean {
  // Structural check (not instanceof): atob throws a DOMException, which does not
  // reliably satisfy `instanceof Error` across VM realms (e.g. under Jest).
  return typeof error === 'object' && error !== null && (error as { name?: unknown }).name === 'InvalidCharacterError';
}

// Central error handler. Handlers themselves return their stable error codes via
// reply.send; this only catches THROWN errors: Zod validation, malformed base64,
// the auth plugin's 401/403, and anything unexpected. It maps client errors to a
// stable code and, crucially, never leaks a 5xx's message/stack to the client.
export function errorHandler(error: FastifyError, request: FastifyRequest, reply: FastifyReply): FastifyReply {
  // A ZodError is a handler's own `.parse()` throwing; a Fastify validation
  // error (`error.validation` set, code FST_ERR_VALIDATION) is the same failure
  // surfaced by the Zod validator compiler when a route validates via its
  // `schema`. Both are malformed input and map to the one stable 400 code.
  if (error instanceof ZodError || isBase64DecodeError(error) || Array.isArray((error as { validation?: unknown }).validation)) {
    return reply.status(400).send({ code: API_ERROR_INVALID_REQUEST });
  }

  const statusCode = typeof error.statusCode === 'number' ? error.statusCode : 500;

  if (statusCode >= 400 && statusCode < 500) {
    // Auth errors already carry a stable lowercase `code`; fall back for the rest.
    return reply.status(statusCode).send({ code: (error as { code?: string }).code ?? API_ERROR_INVALID_REQUEST });
  }

  // Server error: log the detail server-side, expose only a generic code.
  request.log.error(error);

  return reply.status(500).send({ code: API_ERROR_INTERNAL });
}

interface CreateServerOptions {
  /**
   * Register @fastify/swagger so `app.swagger()` can emit the OpenAPI document
   * from the routes' Zod schemas. Off by default: the spec describes the whole
   * API surface and is only ever generated by the build script, never served.
   * Must be registered BEFORE the routes, which is why it lives here.
   */
  openapi?: boolean;
}

export async function createServer(options: CreateServerOptions = {}) {
  const app = Fastify({
    logger: {
      level: isDev ? 'debug' : 'info',
    },
  });

  app.setErrorHandler(errorHandler);
  attachApiErrorMessages(app);

  if (options.openapi) {
    const fastifySwagger = (await import('@fastify/swagger')).default;
    const { jsonSchemaTransform } = await import('fastify-type-provider-zod');

    await app.register(fastifySwagger, {
      openapi: {
        info: { title: 'Encryption service API', version: '1.0.0' },
        servers: [{ url: '/' }],
      },
      transform: jsonSchemaTransform,
    });
  }

  // Register plugins
  app.register(securityHeadersPlugin);
  app.register(corsPlugin);
  app.register(jwtAuthPlugin);

  // Cross-origin-fetchable assets (email logo, PDF fonts), served on every host.
  const { publicAssetsPlugin } = await import('@encryption/src/server/plugins/public-assets');
  app.register(publicAssetsPlugin);

  if (isDev) {
    // In development, embed Vite dev servers as middleware (vault + UI)
    const { viteDevPlugin } = await import('@encryption/src/server/plugins/vite-dev');
    app.register(viteDevPlugin);

    // Shared in-memory document store for the demo products (dev only, never
    // registered in production). Lets multiple demo instances see one list.
    const { demoRoute } = await import('@encryption/src/server/routes/demo');
    app.register(demoRoute);
  } else {
    // In production, serve pre-built static files
    const { staticVaultPlugin } = await import('@encryption/src/server/plugins/static-vault');
    const { staticUiPlugin } = await import('@encryption/src/server/plugins/static-ui');
    app.register(staticVaultPlugin);
    app.register(staticUiPlugin);
  }

  // Register routes
  app.register(versionRoute);
  app.register(meRoute);
  app.register(publicKeysRoute);
  app.register(vaultRoute);
  app.register(emergencyAccessRoute);

  // `hide` keeps infrastructure endpoints out of the generated OpenAPI document:
  // they are not part of the API the interface consumes.
  const hidden = { schema: { hide: true } };

  // Health check
  app.get('/health', hidden, async () => {
    return { status: 'ok' };
  });

  // Prevent indexing on both domains
  app.get('/robots.txt', hidden, async (_, reply) => {
    reply.type('text/plain').send('User-agent: *\nDisallow: /\n');
  });

  // Browsers auto-request /favicon.ico for any TOP-LEVEL document (iframes
  // never trigger it), so this only fires when someone opens a vault or
  // interface URL directly. Neither domain is meant to be browsed that way and
  // neither ships an icon, so answer 204 rather than let a 404 sit in the
  // console. A `<link rel="icon" href="data:,">` would not work here: the CSP
  // on both hosts restricts `img-src`, and unlike this browser-initiated
  // request, a markup-declared icon is subject to it.
  app.get('/favicon.ico', hidden, async (_, reply) => {
    reply.code(204).send();
  });

  return app;
}
