// Generated by `npm run css:types` from the stylesheet next to it. Do not edit.
declare const styles: {
  readonly footer: string;
  readonly label: string;
  readonly num: string;
  readonly printRoot: string;
  readonly sheet: string;
  readonly title: string;
  readonly warning: string;
  readonly word: string;
  readonly words: string;
};

export default styles;
