{{- if include "encryption.hasInlineSecrets" . }}
{{- $v := .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "encryption.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "encryption.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and $v.database.url (not $v.database.existingSecret.name) }}
  DATABASE_URL: {{ $v.database.url | quote }}
  {{- end }}
  {{- if and $v.database.migration.enabled $v.database.migration.url (not $v.database.migration.existingSecret.name) }}
  MIGRATOR_DATABASE_URL: {{ $v.database.migration.url | quote }}
  {{- end }}
  {{- if and $v.sentry.enabled $v.sentry.dsn (not $v.sentry.existingSecret.name) }}
  SENTRY_DSN: {{ $v.sentry.dsn | quote }}
  {{- end }}
  {{- if and (or $v.config.mailer.user $v.config.mailer.password) (not $v.config.mailer.existingSecret.name) }}
  MAILER_SMTP_USER: {{ $v.config.mailer.user | quote }}
  MAILER_SMTP_PASSWORD: {{ $v.config.mailer.password | quote }}
  {{- end }}
  {{- if and (or $v.config.mailer.fallback.user $v.config.mailer.fallback.password) (not $v.config.mailer.fallback.existingSecret.name) }}
  MAILER_FALLBACK_SMTP_USER: {{ $v.config.mailer.fallback.user | quote }}
  MAILER_FALLBACK_SMTP_PASSWORD: {{ $v.config.mailer.fallback.password | quote }}
  {{- end }}
{{- end }}
